### PR TITLE
Themes for online manual

### PR DESCRIPTION
**Pull request by pau4o**
- Original theme for site
- Original theme modified a bit to increase contrast
- Solarized dark theme based on xterm colours
- Black on white

### CODE REVIEW

**Comment by tarsius** [comment]
Please also:

* [ ] Make sure [LibreJS](https://www.gnu.org/software/librejs/) is happy. See https://github.com/melpa/melpa/issues/3731 for context. :innocent: 
* [ ] Make sure EU bureaucrats are happy, by showing a popup "by using a cookie you are using a cookie" when choosing a theme and the cookie does not exist yet. :frowning_face:

**Comment by tarsius** [comment]
Very nice, by the way. Thanks!

**Comment by tarsius** [comment]
I have uploaded a preview to http://preview.magit.vc.s3-website.eu-central-1.amazonaws.com.

One of the manuals is patched to use the themes: http://preview.magit.vc.s3-website.eu-central-1.amazonaws.com/manual/magit.html. For now I have done that manually, see https://github.com/magit/magit/compare/master...css-style.

**Comment by pau4o** [comment]
@tarsius we don't use cookies, and even we use them we don't need to show cookie notification as it's not used for tracking users.

**Comment by tarsius** [comment]
While we do store some information that we *could* (I believe) we send to the server on a later visit, we don't actually do that. All themes are always downloaded right? So since we don't do something cookie-like, we should be save, agreed.

**Comment by tarsius** [comment]
@pau4o So this is mostly ready. Will you have some time to work on the two remaining changes that I requested soonish?

**Comment by tarsius** [comment]
I like the menu but find it to distracting, which is why I requested that you move it to the edge of the window. Something we should consider doing in addition to that is to dim it until the user moves the mouse over it.

**Comment by pau4o** [comment]
@tarsius check new commits, hopefully they resolve all of your issues except **LibreJS**

**Comment by pau4o** [comment]
I installed **LibreJS** and it blocks even [quotes.js](magit.vc/quotes/quotes.js)

When I add proper header to [simple-css-switch.js](magit.vc/assets/js/simple-css-switch.js) It will be permitted to load but `<body onload="..."` will be blocked. And I can't find how to resolve this issue.

**Comment by tarsius** [comment]
> And I can't find how to resolve this issue.

Thanks for trying. Sounds like LibreJS isn't easy to satisfy. Well we tried. That's good enough :roll_eyes:

**Comment by tarsius** [comment]
> Show string "themes" instead of the actual menu

I don't see this.

**Comment by tarsius** [comment]
... but that kinda conflicts with the dimming anyway. Which I like, except that because you replaced the numbers with the theme names I still find the menu to intrusive. How about dimming *and* only showing the theme names on however?

**Comment by pau4o** [comment]
> How about dimming and only showing the theme names on hover?

just revert last commit bf224b9a456b55f72c3a0b517fb1c99556a63fa1

**Comment by tarsius** [comment]
I think there was a misunderstanding, when I said:

> Show string "themes" instead of the actual menu

I meant "Show the string `"themes"` and nothing else. Only once the user hovers over that text show the menu.

This idea obviously conflicts with "dim the menu unless hover" since there is no menu that could be dimmed when the mouse is elsewhere. (If you want to experiment with this, please do, otherwise I think I will go with what you have already implemented.)

>> How about dimming and only showing the theme names on hover?

> just revert last commit bf224b9

Not quite. Having cleared up the above misunderstanding, these are the two states I had in mind:

* hover => show colorful menu with theme names such as "default".
* not hover => show dimmed menu with numbers such as "0".

**Comment by tarsius** [comment]
I have rebased your branch onto `master` and then merged the result, except for the last commit into that branch.

Thanks so much again!

I leave this open so we can discuss my last suggestions.

**Comment by pau4o** [comment]
Next week I will deal with the latest idea that we discuss.

**Comment by tarsius** [comment]
Thanks! (There's no hurry.)

**Comment by tarsius** [comment]
What we have now works for me.

**Pull request closed without merging**
